name: Update readme.io documentation
on:
  push:
    branches:
      - main
jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update readme.io documentation
        uses: apivideo/api.video-readmeio-document-sync-action@1.2
        with:
          document-slug: react-native-live-stream
          markdown-file-path: README.md
          readme-io-api-key: ${{ secrets.README_IO_API_KEY }}
          make-relative-links-absolute: true
